server:
  port: 8000

solon:
  app:
    name: example

# Logger Config
solon.logging.logger:
  "mybatis.mate":
    level: DEBUG
  "com.zaxxer":
    level: WARN


# FlowLong Config
flowlong:
  remind:
    cron: "*/5 * * * * ?"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/flowlong?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
