server:
  port: 8000

solon:
  app:
    name: example

# Logger Config
solon.logging.logger:
  "mybatis.mate":
    level: DEBUG


# FlowLong Config
flowlong:
  remind:
    cron: "*/5 * * * * ?"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/flowlong?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

# Mybatis-Plus Config
mybatis.flowlong:
  mappers:
    - "com.flowlong.bpm.mybatisplus.mapper.*"
