name: Publish package to the Maven Central Repository
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build without tests
        run: ./gradlew build -x test

      - name: Publish
        run: ./gradlew publishAllPublicationsToOSSRHRepository
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
